Make tooltip device independent interactable
getethos/ethos-design-system pull request #489
Opened 2023-01-28 00:05 UTC by EvitaAFD

## [GC-1078](https://ethoslife.atlassian.net/browse/GC-1078?atlOrigin=eyJpIjoiZWRjOGY1ZWRiNmI0NDg4ODg4ZWU3MjYxMmFmZTlmYjciLCJwIjoiaiJ9)
[GC-1076](https://ethoslife.atlassian.net/browse/GC-1076?atlOrigin=eyJpIjoiZGZmMzczNmRhZmNlNDkxM2I2ZmNjZjRiNWZhNjBlYjMiLCJwIjoiaiJ9)

### Please review these reminders and either check the box or explain why not:

- [x] Read and followed the [contributing guidelines](https://eds.eks.dev.ethos-int.com/#/Guidelines?id=section-contribute)?
- [x] Component is exported from [index.js](https://github.com/getethos/ethos-design-system/blob/master/src/components/index.js)?
- [x] Type is exported from [index.d.ts](https://github.com/getethos/ethos-design-system/blob/master/src/components/index.d.ts) so Typescript users can consume it? Added a test and ran `yarn test:types`?
- [ ] Bumped the yarn version?

### Referencing PR or Branch (e.g. in CMS or monorepo):

- https://ethoslife.atlassian.net/browse/GC-1076?atlOrigin=eyJpIjoiZGZmMzczNmRhZmNlNDkxM2I2ZmNjZjRiNWZhNjBlYjMiLCJwIjoiaiJ9
- https://ethoslife.atlassian.net/browse/GC-1078?atlOrigin=eyJpIjoiZWRjOGY1ZWRiNmI0NDg4ODg4ZWU3MjYxMmFmZTlmYjciLCJwIjoiaiJ9

### Screenshots and extra notes:

2023-01-31 20:54 UTC, EvitaAFD commented on src/components/Tooltip/Tooltip.js
> +                role="button"
The role is required for this to be seen as interactive and therefore allow the user to tab through the page and open the tooltip, divs shouldn't have a tabIndex on them unless you specify that they are in fact an interactive element, in this case the div is acting like a button, so this is the appropriate role.

2023-01-31 20:56 UTC, EvitaAFD commented on src/components/Tooltip/Tooltip.js
> +                tabIndex={0}
The tabIndex paired with the onFocus and onBlur are what allow users who rely solely on the keyboard to navigate the screen to be able to interact with this element

2023-01-31 21:42 UTC, t1mwillis commented on src/components/Tooltip/Tooltip.js
> +                aria-labelledby="info-tooltip"
```suggestion
                ariaLabelledBy="info-tooltip"
```

2023-01-31 21:44 UTC, t1mwillis commented
Ultimately this looks good to me. A couple questions:
* Is there anyway to "check" our work here? Can we run an audit on the deploy preview?
* A little higher in the file, there are some `HEADER_ID` & `DESC_ID` variables, does it make sense to use those for our `labeledBy` value?

2023-01-31 21:56 UTC, EvitaAFD commented
> Ultimately this looks good to me. A couple questions:
> 
> * Is there anyway to "check" our work here? Can we run an audit on the deploy preview?
> * A little higher in the file, there are some `HEADER_ID` & `DESC_ID` variables, does it make sense to use those for our `labeledBy` value?

I tested it in the styleguide, you can see the screenshot in the PR where the focus box is on the 'i' icon- you can try to test this navigating your webpage using the tab key, you can enable a focus box in your accessibility settings to help make it more obvious that an element is selected. I am not familiar with those variables - are they specifically for accessibility?

2023-01-31 22:43 UTC, t1mwillis commented
OK -- I'll have to do some accessibility testing reading!

Those variables are are used by the "mobile" version of the tooltip, the modal. Check out line 61 in the file. Mostly just asking if it makes sense to use them for the icon, or at least declare them similarly as constants instead of the magic string `info-tooltip`. Up to you!

2023-01-31 22:45 UTC, t1mwillis approved these changes

2023-01-31 23:14 UTC, t1mwillis requested changes
Actually, let's commit that suggestion so we don't run into linter issues!

2023-02-01 19:58 UTC, t1mwillis commented on src/components/Tooltip/Tooltip.js
> +const ACCESSIBILTY_ID = 'info-tooltip'
```suggestion
const ACCESSIBILITY_ID = 'info-tooltip'
```

2023-02-01 19:58 UTC, t1mwillis commented on src/components/Tooltip/Tooltip.js
> +const ACCESSIBILTY_ID = 'info-tooltip'
Then let's get this in!

2023-02-01 21:52 UTC, t1mwillis approved these changes

2023-02-01 21:57 UTC, merged