[MAR-724] universnal nav bar redesign
getethos/ethos-design-system pull request #500
Opened 2023-05-23 07:38 UTC by darkul1

## [Jira Task](https://ethoslife.atlassian.net/browse/MAR-724)

### Please review these reminders and either check the box or explain why not:

- [x] Read and followed the [contributing guidelines](https://eds.eks.dev.ethos-int.com/#/Guidelines?id=section-contribute)?
- [ ] Component is exported from [index.js](https://github.com/getethos/ethos-design-system/blob/master/src/components/index.js)?
- [ ] Type is exported from [index.d.ts](https://github.com/getethos/ethos-design-system/blob/master/src/components/index.d.ts) so Typescript users can consume it? Added a test and ran `yarn test:types`?
- [x] Bumped the yarn version?

### Referencing PR or Branch (e.g. in CMS or monorepo):
# [Deploy Preview](https://deploy-preview-7366--ethos-cms.netlify.app/)

### Screenshots and extra notes:
![image](https://github.com/getethos/ethos-design-system/assets/132548594/9eb8cfb9-3546-49c7-9491-b549cabb90ca)

![image](https://github.com/getethos/ethos-design-system/assets/132548594/adfcdaf2-b551-428c-9253-a877ca8921ce)

2023-05-24 12:23 UTC, arnas007 approved these changes

2023-05-25 07:22 UTC, coleEthos commented on src/components/UniversalNavbarExpanded/CtaButton.module.scss
> +@import '../Variables.scss';
Why did this need to be added?

2023-05-25 07:25 UTC, coleEthos reviewed
Overall code LGTM. Will wait until final design QA from Loc has been addressed and CMS PR has been updated with latest (both consumer and agents menu links) before approving. Nice work Darius!

2023-06-03 00:42 UTC, coleEthos requested changes
Can we eliminate the shifting of the text when bolded, so it functions like the old bolding of text when hovered? After that I think this is good to go!

See in attached screen recording how the text shifts left to right when bolded upon hover, but does not move on staging.

https://github.com/getethos/ethos-design-system/assets/87672141/0a009820-6236-4fd3-8c46-00f651662906

2023-06-08 05:58 UTC, darkul1 commented
> Can we eliminate the shifting of the text when bolded, so it functions like the old bolding of text when hovered? After that I think this is good to go!
> 
> See in attached screen recording how the text shifts left to right when bolded upon hover, but does not move on staging.
> 
>  Screen.Recording.2023-06-02.at.5.40.46.PM.mov

@coleEthos resolved this!

2023-06-09 05:58 UTC, coleEthos requested changes
Could we make one more minor change here? Make the clickable area the button only, so you don't accidentally click this CTA when expanding/closing accordion menus on the right side of the screen? I did this once when testing on my phone. 

![Screen Shot 2023-06-08 at 10 57 14 PM](https://github.com/getethos/ethos-design-system/assets/87672141/31b81d49-1a43-499c-8d75-84690269009c)

2023-06-09 06:57 UTC, coleEthos approved these changes
LGTM, remember to add git tag with version number as described in readme, before or after merge!

2023-06-09 07:52 UTC, merged