Aj/gc 2393 forbes logo
getethos/ethos-design-system pull request #504
Opened 2023-08-04 07:08 UTC by andriusjurkevicius

## [Jira Task](https://ethoslife.atlassian.net/browse/GC-2393)

### Please review these reminders and either check the box or explain why not:

- [x] Read and followed the [contributing guidelines](https://eds.eks.dev.ethos-int.com/#/Guidelines?id=section-contribute)?
- [x] Bumped the yarn version?

### Screenshots and extra notes:

2023-08-04 07:20 UTC, coleEthos requested changes
This will potentially be used by different partners in the future. Could we consider making this feature not specific towards any specific partner and just allow for CMS/Main app to pass in a logo / logo size parameter to the EDS navbar? EDS could also specify different logo sizes if that's easier. Instead of "forbesLogo" here in the code, it could just be "partnerLogo".

2023-08-08 17:24 UTC, coleEthos commented on src/components/UniversalNavbarExpanded/MobileNav/MobileNav.js
> +  partnerLogo,
@andriusjurkevicius please add this param to JSDocs above and include specifications for how to use, like image size/format/etc.

2023-11-22 22:14 UTC, siddrajpoot approved these changes

2023-11-22 22:49 UTC, coleEthos approved these changes
@siddrajpoot after merging make sure you push the git tag for the new version as described in the readme.

2023-11-27 18:50 UTC, merged